### ISSUE TITLE
tuples and lists are converted to same json code

### ISSUE THREAD

**Issue by peendebak** [hgrecco/serialize#3]
To make tuples have a unique representation, I used
```
def __serialize_tuple(c):
    print('tuple!')
    return serialize_module.dumps(c)

def __unserialize_tuple(s):
    return tuple(serialize_module.loads(s)) 

fmt = 'json'
serialize_module.register_class(tuple, __serialize_tuple, __unserialize_tuple)

print(serialize_module.dumps( [1,2], fmt ) )
print(serialize_module.dumps( (1,2), fmt ) )
```
But this has no effect.

**Comment by hgrecco** [comment]
Because python JSON dumper works by calling these extra methods only when it does not recognize the type. AFAIK there is not way to do it the other way around (i.e. override the encoding).

It could be implemented easily, though.

**Comment by peendebak** [comment]
@hgrecco Can you eloborate on what you mean by "It could be implemented easily" if there is no way to override the encoding?

**Comment by hgrecco** [comment]
Serialize provides a common API for 8 serialization packages and very easy to add more. This API includes way to register custom classes for serialization/deserialization. We do it, when possible, by using the infrastructure provided by those packages. In particular, Python's json package works by trying first to identify and only if not found call the extensions (See [here](https://github.com/python/cpython/blob/master/Lib/json/encoder.py#L438) )

I think the easiest (but not cleanest) way is to monkey patch `_make_iterencode` to change this.

**Comment by hgrecco** [comment]
Thanks, Implemented will be in the next realease
