### ISSUE TITLE
can't serialize an object

### ISSUE THREAD

**Issue by kylefoley76** [hgrecco/serialize#6]
When I run this code:

`hey = 'you'
with open('output.json', 'wb') as fp:
    pyarrow.serialize(hey, fp)`

I get the error message:

    pyarrow.serialize(hey, fp)
TypeError: Argument 'context' has incorrect type (expected pyarrow.lib.SerializationContext, got _io.BufferedWriter)

**Comment by hgrecco** [comment]
You should contact the pyarrow devs for this. This method is not part of the serialize package, it just has the same name
